### ISSUE TITLE
The Movie DB Causing Crash

### ISSUE THREAD

**Issue by yensid** [griff/metaz#90] opened 2013-11-27 03:22 UTC
When trying to get metadata for a couple movies (Avatar and Thumbelina), MetaZ would crash.  

I narrowed to down to The Movie DB search causing the crash.  When I disabled Auto Search, it would not crash until I forced a search.  Then I started disabling the search plug-ins one by one.  When The Movie DB is disabled, no crash.

I am using version 1.0a14 on 10.9.

It is not all movies, some work, some do not.

**Comment by griff** [comment] 2013-11-27 13:59
This is a duplicate of #83 which should be fixed with the just released version 1.0a15

**Closed as completed by griff** 2013-11-27 13:59 UTC

**Comment by yensid** [comment] 2013-11-28 00:44
Thanks for the fix, and everything.
