### ISSUE TITLE
The Movie DB Not showing Query Results

### ISSUE THREAD

**Issue by n8murillo** [griff/metaz#77] opened 2013-10-12 13:00 UTC
I have used MetaZ for sometime now and it been an awesome application. Recently I have run into an issue for the first time. I mainly use MetaZ to only query for Movie titles and really like the "The Movie DB" layout because of their move cover images they have available and movie content text. Anyways when I initiate a query for a move all I am getting are results from "Tag Chimp "nothing from "The Movie DB". Is there a work around or bug that I couldn't find in the foams?

Oh I have restarted the application multiple times and uninstalled/reinstall the application as well.

2013-10-12 08:54:12.700 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:] Sent request to tagChimp:
2013-10-12 08:54:12.700 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:]     'videoKind' -> 'Movie'
2013-10-12 08:54:12.701 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:]     'limit' -> '200'
2013-10-12 08:54:12.701 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:]     'title' -> 'ITALIAN'
2013-10-12 08:54:12.701 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:]     'type' -> 'search'
2013-10-12 08:54:12.701 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:]     'token' -> '8363185134824C8CD908AA'
2013-10-12 08:54:12.701 MetaZ[21700:c07] [lvl=1] -[TagChimpPlugin searchWithData:delegate:queue:]     'totalChapters' -> '16'
2013-10-12 08:54:12.702 MetaZ[21700:c07] [lvl=1] -[MZASISearchResult addToQueue:] Sending request to https://tagchimp.com/ape/search.php?limit=200&title=ITALIAN&token=8363185134824C8CD908AA&totalChapters=16&type=search&videoKind=Movie
2013-10-12 08:54:12.702 MetaZ[21700:c07] [lvl=1] -[TheMovieDbPlugin searchWithData:delegate:queue:] Sent request to TheMovieDb
2013-10-12 08:54:12.778 MetaZ[21700:c07] [lvl=1] -[SearchController finishedSearch:] Finished search 0

**Comment by Treverr** [comment] 2013-10-13 23:18
They are working on a fix for this in Issue 74.

**Comment by griff** [comment] 2013-11-10 06:34
Closing this as a duplicate of #74

**Closed as completed by griff** 2013-11-10 06:34 UTC
