### ISSUE TITLE
Doesn't work in High Sierra

### ISSUE THREAD

**Issue by TomStenson** [griff/metaz#167] opened 2017-09-26 16:01 UTC
I just installed 10.13 High Sierra, and MetaZ doesn't accept any files anymore, not through drag and drop, nor via Open in menu. There are no messages, it just doesn't do it.
I'm talking about the official release version of 10.13, not a beta.

**Comment by scottswedorski** [comment] 2017-09-26 19:23
Take a look at this discussion:
https://github.com/griff/metaz/issues/166

We are trying to get some donations for these amazing programmers.

**Comment by griff** [comment] 2017-09-27 22:55
Closing this as a duplicate of #166 which also should be fixed in [Beta 34](https://github.com/griff/metaz/releases/download/v1.0.beta-34/MetaZ-1.0.beta-34.zip)

**Closed as completed by griff** 2017-09-27 22:55 UTC
