### ISSUE TITLE
Can't add multiple files (anymore)

### ISSUE THREAD

**Issue by horzes** [griff/metaz#91] opened 2013-12-03 11:56 UTC
Hello,

First of all thank you for this great software!

Just updated to the latest version. After that, I am not able to work on more than one file at a time anymore.

If I select multiple files and try to open them, only one will open.

Drag and drop doesn't work either.

I downgraded back to 1.0a15, but now also that gives me the same issue.

I'm using OS 10.7.5.

Thank you.

**Comment by griff** [comment] 2013-12-07 12:51
Does it show an alert or does it simply ignore all the other files?

And could you look in the log and tell me what it says? You open the log via the menu Help -> View Log

**Comment by horzes** [comment] 2013-12-08 08:16
Hello,

No alert displayed - as you say, it ignores the other files.

Another thing I noticed: the files are +actually all open+, but I can't see more than one at once. If I save the one file open, then the window closes and only then the next file appears.

In other words, the files are all open, but I can edit only one at the time, which is a bi excruciating for the work I do : )

Thanks you for your help.

Log:

2013-12-08 08:07:18.262 MetaZ[12634:807] <MetaEditPanel: 0x10192cd80>: the delegate <ResizeController: 0x101b45f20> was sent -splitView:resizeSubviewsWithOldSize: and left the subview frames in an inconsistent state:
2013-12-08 08:07:18.263 MetaZ[12634:807] Split view bounds: {{0, 0}, {1662, 803}}
2013-12-08 08:07:18.263 MetaZ[12634:807]     Subview frame: {{0, 0}, {150, 661}}
2013-12-08 08:07:18.263 MetaZ[12634:807]     Subview frame: {{159, 0}, {1258, 803}}
2013-12-08 08:07:18.264 MetaZ[12634:807]     Subview frame: {{1426, 0}, {386, 803}}
2013-12-08 08:07:18.264 MetaZ[12634:807] The outer edges of the subview frames are supposed to line up with the split view's bounds' edges. NSSplitView is working around the problem, perhaps at the cost of more redrawing. (This message is only logged once per NSSplitView.)
2013-12-08 08:07:18.281 MetaZ[12634:807] [lvl=2] -[SearchController doSearch:] Starting search 1
2013-12-08 08:07:18.282 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Add to iTunes.scpt'
2013-12-08 08:07:18.283 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AlertWindowPlugin.mzactions'
2013-12-08 08:07:18.283 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
2013-12-08 08:07:18.284 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Example Actions.scpt'
2013-12-08 08:07:18.284 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions'
2013-12-08 08:07:18.284 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'
2013-12-08 08:07:18.285 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Quit MetaZ.scpt'
2013-12-08 08:07:18.285 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TagChimp.mzsearchprovider'
2013-12-08 08:07:18.285 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'
2013-12-08 08:07:18.285 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'
2013-12-08 08:07:18.286 MetaZ[12634:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Update iTunes.scpt'
2013-12-08 08:07:18.324 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'
2013-12-08 08:07:18.325 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.AlertWindowPlugin'
2013-12-08 08:07:18.327 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.AtomicParsleyPlugin'
2013-12-08 08:07:18.327 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Example Actions'
2013-12-08 08:07:18.329 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.GrowlPlugin'
2013-12-08 08:07:18.329 MetaZ[12634:807] [lvl=1] -[MZMultiGrowlWrapper load] path: /Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1
2013-12-08 08:07:18.331 MetaZ[12634:807] [lvl=2] -[MZMultiGrowlWrapper load] Using Growl.framework 1.3.1 (1.3.1)
2013-12-08 08:07:18.415 MetaZ[12634:807] [lvl=3] -[MZPluginController loadPluginFromSource:error:] Plugin org.maven-group.metaz.plugin.OSXNotificationPlugin requires at least Mac OS X version 10.8.0, but is being run on 10.7.5, and so is ignored.
2013-12-08 08:07:18.416 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'
2013-12-08 08:07:18.417 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TagChimp'
2013-12-08 08:07:18.418 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheMovieDb'
2013-12-08 08:07:18.420 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheTVDBPlugin'
2013-12-08 08:07:18.420 MetaZ[12634:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Update iTunes'
2013-12-08 08:07:18.421 MetaZ[12634:807] [lvl=1] -[SearchController finishedSearch:] Finished search 0
2013-12-08 08:07:18.495 MetaZ[12634:807] [lvl=1] -[MetaZApplication handleOpenScriptCommand:] Handle open: (
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/What%20is%20the%20greatest%20profession.mov,
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/What_is_the_greatest_profession.mov
) <CFBasicHash 0x100375e70 [0x7fff7f0ebfa0]>{type = mutable dict, count = 1,
entries =>
    0 : <CFString 0x7fff7df7e040 [0x7fff7f0ebfa0]>{contents = ""} = (
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/What%20is%20the%20greatest%20profession.mov,
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/What_is_the_greatest_profession.mov
)
}
2013-12-08 08:07:18.503 MetaZ[12634:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/MyBook 2/01 Compressor Processing Folder/What is the greatest profession.mov -t
2013-12-08 08:07:18.505 MetaZ[12634:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/MyBook 2/01 Compressor Processing Folder/What_is_the_greatest_profession.mov -t
2013-12-08 08:07:18.517 MetaZ[12634:807] [lvl=3] -[MZTaskOperation setErrorString:code:] AtomicParsley failed with exit code 2
2013-12-08 08:07:18.538 MetaZ[12634:807] [lvl=3] -[MZTaskOperation setErrorString:code:] AtomicParsley failed with exit code 2
2013-12-08 08:07:19.491 MetaZ[12634:807] [lvl=3] -[MZMetaLoader loadedFile:] Could no load file '/Volumes/MyBook 2/01 Compressor Processing Folder/What_is_the_greatest_profession.mov'
2013-12-08 08:07:20.163 MetaZ[12634:807] [lvl=3] -[MZMetaLoader loadedFile:] Could no load file '/Volumes/MyBook 2/01 Compressor Processing Folder/What is the greatest profession.mov'
2013-12-08 08:08:04.993 MetaZ[12671:807] <MetaEditPanel: 0x100353af0>: the delegate <ResizeController: 0x101d2e330> was sent -splitView:resizeSubviewsWithOldSize: and left the subview frames in an inconsistent state:
2013-12-08 08:08:04.993 MetaZ[12671:807] Split view bounds: {{0, 0}, {1662, 803}}
2013-12-08 08:08:04.994 MetaZ[12671:807]     Subview frame: {{0, 0}, {150, 661}}
2013-12-08 08:08:04.994 MetaZ[12671:807]     Subview frame: {{159, 0}, {1258, 803}}
2013-12-08 08:08:04.994 MetaZ[12671:807]     Subview frame: {{1426, 0}, {386, 803}}
2013-12-08 08:08:04.995 MetaZ[12671:807] The outer edges of the subview frames are supposed to line up with the split view's bounds' edges. NSSplitView is working around the problem, perhaps at the cost of more redrawing. (This message is only logged once per NSSplitView.)
2013-12-08 08:08:05.013 MetaZ[12671:807] [lvl=2] -[SearchController doSearch:] Starting search 1
2013-12-08 08:08:05.015 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Add to iTunes.scpt'
2013-12-08 08:08:05.015 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AlertWindowPlugin.mzactions'
2013-12-08 08:08:05.016 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/AtomicParsleyPlugin.mzdataprovider'
2013-12-08 08:08:05.016 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Example Actions.scpt'
2013-12-08 08:08:05.017 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions'
2013-12-08 08:08:05.017 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/OSXNotificationPlugin.mzactions'
2013-12-08 08:08:05.017 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Quit MetaZ.scpt'
2013-12-08 08:08:05.018 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TagChimp.mzsearchprovider'
2013-12-08 08:08:05.018 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheMovieDb.mzsearchprovider'
2013-12-08 08:08:05.019 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/TheTVDBPlugin.mzsearchprovider'
2013-12-08 08:08:05.019 MetaZ[12671:807] [lvl=1] -[MZPluginController loadPluginSourceWithName:fromURL:error:] Loading plugin at path '/Applications/MetaZ.app/Contents/PlugIns/Update iTunes.scpt'
2013-12-08 08:08:05.057 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Add to iTunes'
2013-12-08 08:08:05.059 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.AlertWindowPlugin'
2013-12-08 08:08:05.061 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.AtomicParsleyPlugin'
2013-12-08 08:08:05.061 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Example Actions'
2013-12-08 08:08:05.062 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.plugin.GrowlPlugin'
2013-12-08 08:08:05.063 MetaZ[12671:807] [lvl=1] -[MZMultiGrowlWrapper load] path: /Applications/MetaZ.app/Contents/PlugIns/GrowlPlugin.mzactions/Contents/Frameworks/Growl.framework/Versions/1.3.1
2013-12-08 08:08:05.065 MetaZ[12671:807] [lvl=2] -[MZMultiGrowlWrapper load] Using Growl.framework 1.3.1 (1.3.1)
2013-12-08 08:08:05.149 MetaZ[12671:807] [lvl=3] -[MZPluginController loadPluginFromSource:error:] Plugin org.maven-group.metaz.plugin.OSXNotificationPlugin requires at least Mac OS X version 10.8.0, but is being run on 10.7.5, and so is ignored.
2013-12-08 08:08:05.151 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Quit MetaZ'
2013-12-08 08:08:05.152 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TagChimp'
2013-12-08 08:08:05.153 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheMovieDb'
2013-12-08 08:08:05.155 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'org.maven-group.metaz.TheTVDBPlugin'
2013-12-08 08:08:05.156 MetaZ[12671:807] [lvl=2] -[MZPluginController loadPluginFromSource:error:] Loaded plugin 'Update iTunes'
2013-12-08 08:08:05.156 MetaZ[12671:807] [lvl=1] -[SearchController finishedSearch:] Finished search 0
2013-12-08 08:08:05.230 MetaZ[12671:807] [lvl=1] -[MetaZApplication handleOpenScriptCommand:] Handle open: (
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/RV84DSG2%20Before%20Talk.mp4,
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/What%20is%20the%20greatest%20profession.mp4
) <CFBasicHash 0x1003a5290 [0x7fff7f0ebfa0]>{type = mutable dict, count = 1,
entries =>
    0 : <CFString 0x7fff7df7e040 [0x7fff7f0ebfa0]>{contents = ""} = (
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/RV84DSG2%20Before%20Talk.mp4,
    file://localhost/Volumes/MyBook%202/01%20Compressor%20Processing%20Folder/What%20is%20the%20greatest%20profession.mp4
)
}
2013-12-08 08:08:05.238 MetaZ[12671:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/MyBook 2/01 Compressor Processing Folder/What is the greatest profession.mp4 -t
2013-12-08 08:08:05.241 MetaZ[12671:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/MyBook 2/01 Compressor Processing Folder/RV84DSG2 Before Talk.mp4 -t
2013-12-08 08:08:05.278 MetaZ[12671:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/MyBook 2/01 Compressor Processing Folder/RV84DSG2 Before Talk.mp4 -e /var/folders/m0/d_h58jhd4ng2c40jhscwhwlw0000gn/T/MetaZImage_A7E95807-1C4A-4DFB-A075-A0BBCDC2AA24-12671-00017CFE51F74EAF
2013-12-08 08:08:05.281 MetaZ[12671:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch AtomicParsley /Volumes/MyBook 2/01 Compressor Processing Folder/What is the greatest profession.mp4 -e /var/folders/m0/d_h58jhd4ng2c40jhscwhwlw0000gn/T/MetaZImage_F2DDC192-8D50-4F64-867B-91C25EEF57F5-12671-00017CFE5208D2F1
2013-12-08 08:08:05.293 MetaZ[12671:807] [lvl=1] -[MZTaskOperation standardOutputGotData:] AtomicParsley stdout No changes.
2013-12-08 08:08:05.294 MetaZ[12671:807] [lvl=1] -[MZTaskOperation standardOutputGotData:] AtomicParsley stdout No changes.
2013-12-08 08:08:05.300 MetaZ[12671:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch mp4chaps -l /Volumes/MyBook 2/01 Compressor Processing Folder/RV84DSG2 Before Talk.mp4
2013-12-08 08:08:05.303 MetaZ[12671:807] [lvl=1] -[MZTaskOperation startOnMainThread] Launch mp4chaps -l /Volumes/MyBook 2/01 Compressor Processing Folder/What is the greatest profession.mp4
2013-12-08 08:08:10.618 MetaZ[12671:807] [lvl=2] -[SearchController doSearch:] Starting search 1
2013-12-08 08:08:10.621 MetaZ[12671:807] [lvl=1] -[MZASISearchResult addToQueue:] Sending request to https://tagchimp.com/ape/search.php?limit=200&title=RV84DSG2%20Before%20Talk&token=8363185134824C8CD908AA&totalChapters=X&type=search&videoKind=Movie
2013-12-08 08:08:10.622 MetaZ[12671:807] [lvl=1] -[TheMovieDbPlugin searchWithData:delegate:queue:] Sent request to TheMovieDb
2013-12-08 08:08:11.532 MetaZ[12671:807] [lvl=1] -[SearchController finishedSearch:] Finished search 0

**Comment by griff** [comment] 2013-12-08 09:10
Hmm the log didn't say much. When you say the window closes do you mean you have to close it? Because in the log it looks like you try an open two .mov files, quit metaz and then load two .mp4 files.

And can you attach a screenshot of metaz with the files open?

Sent from a parallel universe

**Comment by horzes** [comment] 2013-12-08 09:30
Oh don't mind the .mov files, that was a mistake - I know they are not compatible.

Re Window: I have to save the file (Write) in order for the other "background files" to show up.

I am attaching a screenshot.

![grab](https://f.cloud.github.com/assets/6094978/1700043/f181206a-5fea-11e3-980a-71c27e4aa128.jpg)

One strange thing I noticed: for this screenshot, I named one of the two files I opened with MetaZ "Video 2". When opening it, MetaZ  gives me plenty more videos fetched online via the 'Search' field. Not sure what it means. Usually I'd expect all the videos I open to appear in that list, not one video I opened+more videos linked online?

Thank you.

**Comment by horzes** [comment] 2013-12-08 09:32
This is the videos fetched from the web I meant:

![grab 2](https://f.cloud.github.com/assets/6094978/1700051/a01a449e-5feb-11e3-8cb1-b266c97a5284.jpg)

**Comment by griff** [comment] 2013-12-08 11:28
Looking at the screenshot I can see that your problem is actually the same as issue #84. And after looking more into that I found the cause to be that the guy that did pull request #31 also "simplified" the logic controlling the resizing of the window and the split view which has broken all the little corner cases it was originally handling.

The fix in issue #84 should also work for you i.e. the files list is collapsed and hidden on the left and double clicking the blank space on the left or the little dot in the middle of the blank space should show it again.

I am also closing this issue in favor of #84.

**Closed as completed by griff** 2013-12-08 11:28 UTC
