### ISSUE TITLE
Program freezing

### ISSUE THREAD

**Issue by drizzt90** [griff/metaz#172] opened 2017-11-06 21:24 UTC
I did not change anything. When I drop a .mp4 file into the left hand window now the circle comes up like it wants to open up the window to ask me what type of video file it will be ie. Movie, TV Show, Home Video whatever. It will not open that window and will not proceed anymore...

**Comment by randykato** [comment] 2017-11-08 20:31
I get this same behavior now - after I updated OS X to High Sierra (v10.13.1). It just gets stuck "loading" the file.

EDIT: Just saw the thread below about High Sierra, and the beta works!

**Comment by drizzt90** [comment] 2017-11-09 00:34
I found a thread somewhere. If you download the latest beta build (not the stable release) it fixes it. At least it did for me.

**Comment by griff** [comment] 2017-11-14 03:25
I am closing this as a duplicate of #166

**Closed as completed by griff** 2017-11-14 03:25 UTC

**Comment by drizzt90** [comment] 2017-11-14 06:29
Thanks. I just found #166 and hadn’t had a chance to close it.
